### ISSUE TITLE
The yamllint pre-commit hook errors

### ISSUE THREAD

**Issue by brlin-tw** [the-common/markdownlint-nodejs-config-templates#3]
```output
$ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/jumanjihouse/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/fsfe/reuse-tool.
[INFO] Initializing environment for https://github.com/editorconfig-checker/editorconfig-checker.python.
[INFO] Installing environment for https://github.com/fsfe/reuse-tool.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/adrienverge/yamllint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/brlin/.cache/pre-commit/repo5wnxu_pp/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/brlin/.cache/pre-commit/repo5wnxu_pp
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> [45 lines of output]
          Traceback (most recent call last):
            File "/home/brlin/.cache/pre-commit/repo5wnxu_pp/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/home/brlin/.cache/pre-commit/repo5wnxu_pp/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/home/brlin/.cache/pre-commit/repo5wnxu_pp/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
              return hook(config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
              return self._get_build_requires(config_settings, requirements=[])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
              self.run_setup()
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
              super().run_setup(setup_script=setup_script)
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
              exec(code, locals())
            File "<string>", line 23, in <module>
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
              return distutils.core.setup(**attrs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 158, in setup
              dist.parse_config_files()
            File "/home/brlin/.cache/pre-commit/repo5wnxu_pp/py_env-python3.12/lib/python3.12/site-packages/_virtualenv.py", line 22, in parse_config_files
              result = old_parse_config_files(self, *args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 628, in parse_config_files
              setupcfg.parse_configuration(
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/config/setupcfg.py", line 177, in parse_configuration
              options.parse()
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/config/setupcfg.py", line 500, in parse
              section_parser_method(section_options)
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/config/setupcfg.py", line 475, in parse_section
              self[name] = value
              ~~~~^^^^^^
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/config/setupcfg.py", line 293, in __setitem__
              parsed = self.parsers.get(option_name, lambda x: x)(value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/_vendor/packaging/specifiers.py", line 726, in __init__
              self._specs = frozenset(map(Specifier, split_specifiers))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-_7todnoa/overlay/lib/python3.12/site-packages/setuptools/_vendor/packaging/specifiers.py", line 235, in __init__
              raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
          setuptools.extern.packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=3.5.*'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
Check the log at /home/brlin/.cache/pre-commit/pre-commit.log
```

**Comment by brlin-tw** [comment]
Fixed in the f4e649e976e8 revision.
